### ISSUE TITLE
Inconsistent docs around dataserver indices

### ISSUE THREAD

**Issue by adamcox-genesis** [genesiscommunitysuccess/docs#1385]
The basics of dataservers has an `*Important*` point that `nonUnique` cannot be used in dataserver indices

https://github.com/genesiscommunitysuccess/docs/blob/1137200d30d821658fe15bf754b54732ee86bc7f/docs/03_server/02_data-server/02_basics.md?plain=1#L301

But then the advanced page says you can have both:

https://github.com/genesiscommunitysuccess/docs/blob/1137200d30d821658fe15bf754b54732ee86bc7f/docs/03_server/02_data-server/03_advanced.md?plain=1#L230

Going by the what IntelliJ tells me, it seems like you cannot have `nonUnique` indices.

![image](https://github.com/genesiscommunitysuccess/docs/assets/97162540/83b87b9b-8323-4169-956e-eb35881a7cca)

---

Also, maybe I just haven't been able to find it, there doesn't seem to be any information about whether a table index is used by a dataserver. According to [Jose Pozo](https://stackoverflowteams.com/c/genesis-global/questions/1467/1468?noredirect=1#comment1319_1468):

> No, table indices do not influence dataservers. Dataservers have their own record store with their own indices. By default RECORD_ID will be used as the primary key, which essentially is equivalent to creation date.

which wasn't my assumption. Would appreciate more information around this.

Thanks!

**Comment by wjhendry** [comment]
Thanks for raising this. We shall investigate:
- the inconsistent info
- further information about the role of table indices

**Comment by jacinpoz** [comment]
![image](https://github.com/genesiscommunitysuccess/docs/assets/1674873/b98bb143-9365-4960-a8b6-a499c2dd80ad)

**Comment by dbarros1979** [comment]
This PR is addressing this: https://github.com/genesiscommunitysuccess/docs/pull/1403

**Comment by wjhendry** [comment]
![image](https://github.com/genesiscommunitysuccess/docs/assets/90383531/6e512815-dec9-4380-92cc-1814706d7725)
I have updated the documentation after speaking to Jose. The whole section on ranged queries was in need of re-writing. Thanks for pointing this out.

**Comment by wjhendry** [comment]
Docs have been updated.
